# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: mongousername
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  mongousername: {{ default "" .Values.mongo.mongousername | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: mongopass
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  mongopass: {{ default "" .Values.mongo.mongopass | b64enc | quote }}
